from __future__ import annotations

from fastapi import APIRouter, Depends, Request
from starlette.status import HTTP_200_OK

from app.core.logger import logger
from app.schemas.embedding import EmbeddingRequest
from app.schemas.response import APIResponse
from app.services.embedding.embedding_service import EmbeddingService

router = APIRouter(prefix="/embedding", tags=["Embedding"])


@router.post(
    "/generate",
    response_model=APIResponse,
    status_code=HTTP_200_OK,
    summary="Generate embedding for text",
    description="Generates a vector embedding for the given text using Ollama's nomic-embed-text model.",
)
async def generate_embedding(
    request: EmbeddingRequest,
    http_request: Request,
    embedding_service: EmbeddingService = Depends(),
) -> APIResponse:
    """Generate a vector embedding for the provided text.

    Accepts plain text and returns a 768-dimensional embedding vector
    generated by Ollama's nomic-embed-text model.
    """
    trace_id = getattr(http_request.state, "request_id", "")

    logger.info(
        "Embedding requested [%s] | inputChars=%d",
        trace_id,
        len(request.text),
    )

    result = await embedding_service.generate(
        request=request, trace_id=trace_id
    )

    return APIResponse.success_response(
        message="Embedding generated successfully",
        data=result.model_dump(),
        trace_id=trace_id,
    )