from __future__ import annotations

from fastapi import APIRouter, Depends, Request
from starlette.status import HTTP_200_OK

from app.core.logger import logger
from app.schemas.retrieval import EmbedQueryRequest
from app.schemas.response import APIResponse
from app.services.retrieval.retrieval_service import RetrievalService

router = APIRouter(prefix="/retrieval", tags=["Retrieval"])


@router.post(
    "/embed-query",
    response_model=APIResponse,
    status_code=HTTP_200_OK,
    summary="Generate query embedding for semantic search",
    description="Generates a vector embedding for the given search query using Ollama's nomic-embed-text model.",
)
async def embed_query(
    request: EmbedQueryRequest,
    http_request: Request,
    retrieval_service: RetrievalService = Depends(),
) -> APIResponse:
    """Generate a vector embedding for the provided search query.

    Accepts a search query and returns a 768-dimensional embedding vector
    generated by Ollama's nomic-embed-text model. This embedding can be used
    for pgvector similarity search on the backend.
    """
    trace_id = getattr(http_request.state, "request_id", "")

    logger.info(
        "Query embedding requested [%s] | queryChars=%d",
        trace_id,
        len(request.query),
    )

    result = await retrieval_service.embed_query(
        query=request.query, trace_id=trace_id
    )

    return APIResponse.success_response(
        message="Embedding generated successfully",
        data=result.model_dump(),
        trace_id=trace_id,
    )